export default [
    { id: 'axis0high', name: 'Left X+' },
    { id: 'axis0low', name: 'Left X-' },
    { id: 'axis1high', name: 'Left Y+' },
    { id: 'axis1low', name: 'Left Y-' },
    { id: 'axis2high', name: 'Right X+' },
    { id: 'axis2low', name: 'Right X-' },
    { id: 'axis3high', name: 'Right Y+' },
    { id: 'axis3low', name: 'Right Y-' },
    { id: 'axis4high', name: 'Pad X+' },
    { id: 'axis4low', name: 'Pad X-' },
    { id: 'axis5high', name: 'Pad Y+' },
    { id: 'axis5low', name: 'Pad Y-' },
    { id: 'btn0', name: 'Button 1' },
    { id: 'btn1', name: 'Button 2' },
    { id: 'btn2', name: 'Button 3' },
    { id: 'btn3', name: 'Button 4' },
    { id: 'btn4', name: 'Button 5' },
    { id: 'btn5', name: 'Button 6' },
    { id: 'btn6', name: 'Button 7' },
    { id: 'btn7', name: 'Button 8' },
    { id: 'btn8', name: 'Button 9' },
    { id: 'btn9', name: 'Button 10' },
    { id: 'btn10', name: 'Button 11' },
    { id: 'btn11', name: 'Button 12' },
];
