export default [
    { id: 'axis0high', name: 'Left →' },
    { id: 'axis0low', name: 'Left ←' },
    { id: 'axis1high', name: 'Left ↓' },
    { id: 'axis1low', name: 'Left ↑' },
    { id: 'axis2high', name: 'Right →' },
    { id: 'axis2low', name: 'Right ←' },
    { id: 'axis3high', name: 'Right ↓' },
    { id: 'axis3low', name: 'Right ↑' },
    { id: 'axis4high', name: 'Pad →' },
    { id: 'axis4low', name: 'Pad ←' },
    { id: 'axis5high', name: 'Pad ↓' },
    { id: 'axis5low', name: 'Pad ↑' },
    { id: 'btn0', name: '(1)' },
    { id: 'btn1', name: '(2)' },
    { id: 'btn2', name: '(3)' },
    { id: 'btn3', name: '(4)' },
    { id: 'btn4', name: '(5)' },
    { id: 'btn5', name: '(6)' },
    { id: 'btn6', name: '(7)' },
    { id: 'btn7', name: '(8)' },
    { id: 'btn8', name: '(9)' },
    { id: 'btn9', name: '(10)' },
    { id: 'btn10', name: '(11)' },
    { id: 'btn11', name: '(12)' },
];
